spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true
